server.port: 8080

logging.level.org.springframework.cloud.kubernetes: DEBUG
spring.application.name: client-service

management:
  endpoints:
    web:
      exposure:
        include: info,refresh,keepalive,health

