server.port: 8080

spring:
  application:
    name: cloud-k8s-app
  cloud:
    kubernetes:
      config:
        name: betgeris-dev
        namespace: betgeris-dev
        sources:
          # Spring Cloud Kubernetes will lookup a ConfigMap named c1 in namespace default-namespace
          - name: c1
