   
spring:
  cloud:
    kubernetes:
      config:
        enabled: true
        sources:
          - namespace: default
            name: client-service
      reload:
        enabled: true
        mode: event
        strategy: polling
